language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - phpunit --coverage-text --verbose --configuration tests/phpunit.xml

after_script:
  - vendor/bin/test-reporter
